name: transitioned_indexed_stack
description: This Package helps You Making Animated Transitions between IndexedStack children widgets Easily.
version: 1.0.0
homepage: https://github.com/anasfik/transitioned_indexed_stack
repository: https://github.com/anasfik/transitioned_indexed_stack
documentation: https://github.com/anasfik/transitioned_indexed_stack
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:

environment:
  sdk: ">=2.18.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
